In [29]:
#Regression Model

In [84]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [85]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [86]:

df_train

,id,carat,cut,color,clarity,depth,table,x,y,z,price
0,0,0.30,Ideal,F,SI1,60.2,56.0,4.36,4.41,2.64,6.163
1,1,0.51,Premium,E,SI1,61.5,58.0,5.14,5.11,3.15,7.373
2,2,1.59,Premium,G,SI1,62.1,58.0,7.45,7.43,4.62,9.305
3,3,0.70,Ideal,E,VS2,62.6,57.0,5.63,5.68,3.54,7.990
4,4,1.01,Good,E,VVS1,63.1,59.0,6.31,6.34,3.99,9.265
...,...,...,...,...,...,...,...,...,...,...,...
40450,40450,0.50,Premium,G,SI2,61.9,58.0,5.12,5.09,3.16,6.914
40451,40451,1.07,Ideal,G,SI1,62.2,57.0,6.59,6.56,4.09,8.576
40452,40452,1.42,Very Good,G,VS1,62.7,55.0,7.11,7.17,4.48,9.346
40453,40453,0.42,Ideal,G,VVS2,61.3,56.0,4.81,4.82,2.95,6.938
40454,40454,1.02,Good,H,SI2,61.4,60.0,6.44,6.49,3.97,8.416

In [87]:

df_test

          id  carat        cut color clarity  depth  table     x     y     z
0          0   0.51  Very Good     D     VS1   63.3   57.0  5.07  5.10  3.22
1          1   0.36      Ideal     D     SI1   59.5   56.0  4.63  4.68  2.77
2          2   0.70  Very Good     F     SI1   60.5   56.0  5.73  5.80  3.49
3          3   1.05    Premium     H     VS2   59.0   59.0  6.71  6.68  3.95
4          4   0.50    Premium     E     SI2   59.4   60.0  5.21  5.16  3.08
...      ...    ...        ...   ...     ...    ...    ...   ...   ...   ...
13480  13480   0.61  Very Good     H    VVS2   60.5   57.0  5.52  5.54  3.35
13481  13481   1.22    Premium     G     VS2   61.8   58.0  6.84  6.91  4.25
13482  13482   0.33  Very Good     D     SI1   61.5   60.0  4.41  4.44  2.72
13483  13483   2.17      Ideal     I     SI1   60.4   56.0  8.36  8.43  5.07
13484  13484   0.54    Premium     E     SI1   61.6   61.0  5.23  5.20  3.21

[13485 rows x 10 columns]

In [88]:
#asigna un valor numÃ©rico a cada tipo de cut.
#asigna un valor numÃ©rico a cada tipo de clarity.

In [89]:
cut_type = {
    'Ideal': 5,
    'Premium': 4,
    'Very Good': 3,
    'Good': 2,
    'Fair': 1
}

df_train['cut'] = df_train['cut'].map(cut_type)

In [90]:
color_type = {
    'D': 7,
    'E': 6,
    'F': 5,
    'G': 4,
    'H': 3,
    'I': 2,
    'J': 1
}

df_train['color'] = df_train['color'].map(color_type)

In [91]:
clarity_type = {
    'IF': 8,
    'VVS1': 7,
    'VVS2': 6,
    'VS1': 5,
    'VS2': 4,
    'SI1': 3,
    'SI2': 2,
    'I1': 1

}

df_train['clarity'] = df_train['clarity'].map(clarity_type)

In [92]:
print(df_train.shape[0])
df_train.sample()

40455

,id,carat,cut,color,clarity,depth,table,x,y,z,price
22833,22833,0.52,5,7,3,62.4,57.0,5.18,5.14,3.22,7.45

In [93]:
print(df_test.shape[0])
df_test.sample()

13485

        id  carat    cut color clarity  depth  table     x     y     z
7595  7595   0.74  Ideal     E     VS2   61.9   57.0  5.81  5.78  3.59

In [94]:
#se calcula la matriz de correlaciones entre todas las columnas del conjunto de datos del train.

In [95]:
corr_mat = df_train.corr()

In [96]:
df_train.drop(['depth','table'], axis = 1, inplace = True)

In [97]:
df_train

          id  carat  cut  color  clarity     x     y     z  price
0          0   0.30    5      5        3  4.36  4.41  2.64  6.163
1          1   0.51    4      6        3  5.14  5.11  3.15  7.373
2          2   1.59    4      4        3  7.45  7.43  4.62  9.305
3          3   0.70    5      6        4  5.63  5.68  3.54  7.990
4          4   1.01    2      6        7  6.31  6.34  3.99  9.265
...      ...    ...  ...    ...      ...   ...   ...   ...    ...
40450  40450   0.50    4      4        2  5.12  5.09  3.16  6.914
40451  40451   1.07    5      4        3  6.59  6.56  4.09  8.576
40452  40452   1.42    3      4        5  7.11  7.17  4.48  9.346
40453  40453   0.42    5      4        6  4.81  4.82  2.95  6.938
40454  40454   1.02    2      3        2  6.44  6.49  3.97  8.416

[40455 rows x 9 columns]

In [98]:
#El conjunto de datos de entrenamiento se divide en variables independientes X (todas las columnas excepto "precio") y la variable dependiente y ("precio").

In [99]:
X = df_train.iloc[:,:-1]
y = df_train['price']

In [100]:
model = RandomForestRegressor(max_depth = 70, min_samples_leaf = 4, min_samples_split = 10, n_estimators = 400)
model.fit(X, y)

RandomForestRegressor(max_depth=70, min_samples_leaf=4, min_samples_split=10,
                      n_estimators=400)

In [101]:
#same transformations applied to the training dataset are applied to the corresponding columns in the test dataset (df_test). Then, the "depth" and "table" columns are dropped from the test dataset.

In [102]:
df_test['cut'] = df_test['cut'].map(cut_type)
df_test['color'] = df_test['color'].map(color_type)
df_test['clarity'] = df_test['clarity'].map(clarity_type)
df_test.drop(['depth', 'table'], axis = 1, inplace = True)

In [103]:
# Los precios de los diamantes en este caso, se predicen utilizando el modelo entrenado y los datos de prueba.

In [104]:
y_pred = model.predict(df_test)
y_pred

array([7.50164729, 6.51744049, 7.76701464, ..., 6.38905943, 9.7520369 ,
       7.32014099])

In [105]:
# Los valores pronosticados se aÃ±aden como una nueva columna ("price") en el test dataset (df_test).

In [106]:
df_test['price'] = y_pred
df_for_submission = df_test[["id", "price"]]

In [107]:
df_for_submission.to_csv("my_submission.csv", index=False)